version: '3.9'
services:
  nginx:
    image: nginx
    volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./public:/app/public
    ports:
      - "80:80"
      - "443:443"
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
    - .:/app
    links:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=shop-docker-server
      HOST_MACHINE_MYSQL_PORT: 3306
  database:
    image: mariadb
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/app
    working_dir: /app

volumes:
  laravel-storage:
  laravel-cache:
  composer-vendor:
  npm-node_modules:
